spotlight:
  url: https://arc.msn.com/v3/Delivery/Placement?pid=${pid}&fmt=json&rafb=0&ua=WindowsShellClient%2F0&cdm=1&disphorzres=9999&dispvertres=9999&lo=80217&pl=${language}&lc=${language}&ctry=${country}&time=${time}
  pid: 209567
  country: random
  language: en-US

general:
  port: 8000
  output.dir: c:/tmp/images
  sleep.time: 3
  initial.sleep.time: 0
  imagesPerPage: 15
  json.filename: images_database.jsonl