spotlight:
  url: https://arc.msn.com/v3/Delivery/Placement?pid=${pid}&fmt=json&rafb=0&ua=WindowsShellClient%2F0&cdm=1&disphorzres=9999&dispvertres=9999&lo=80217&pl=${language}&lc=${language}&ctry=${country}&time=${time}
  pid: 209567
  language: en-US

general:
  home.url: http://localhost:8000
  port: 8000
  output.dir: /tmp/images
  sleep.time: 0
  initial.sleep.time: 0
  imagesPerPage: 10
  json.filename: images_database.jsonl

notification.email:
  # images: 500
  # sender:
  # password:

notification.telegram:
  # images: 500
  # token:
  # chatId:

ad:
  - Microsoft
  - AI
  - XP League
  - Meet the creators
  - Bing
  - Father's Day
  - Read the story